HubSpot/hubspot-api-ruby

CHANGELOG.md, Gemfile.lock, lib/hubspot/version.rb, spec/features/communication_preferences/definition_api_spec.rb, spec/features/communication_preferences/status_api_spec.rb
Codegen: https://github.com/HubSpot/hubspot-api-ruby/pull/108
=> Communication preferences spec

lib/hubspot/discovery/base_api_client.rb, spec/discovery/base_api_client_spec.rb
Old
```ruby
properties = {
"company": "Biglytics",
"email": "bcooper@biglytics.net",
"firstname": "Bryan",
"lastname": "Cooper",
"phone": "(877) 929-0687",
"website": "biglytics.net"
}
simple_public_object_input = Hubspot::Crm::Contacts::SimplePublicObjectInput.new(properties: properties)
api_response = api_client.crm.contacts.basic_api.create(simple_public_object_input: simple_public_object_input)
```
New
```ruby
properties = {
"company": "Biglytics",
"email": "bcooper@biglytics.net",
"firstname": "Bryan",
"lastname": "Cooper",
"phone": "(877) 929-0687",
"website": "biglytics.net"
}
body = {
properties: properties
}
api_response = api_client.crm.contacts.basic_api.create(body: body)
```
Old
```ruby
filter = ::Hubspot::Crm::Contacts::Filter.new(
property_name: 'firstname',
operator: 'EQ', …
```
=> Params objects

CHANGELOG.md, Gemfile.lock, lib/hubspot/discovery/base_api_client.rb, lib/hubspot/version.rb, spec/discovery/base_api_client_spec.rb
Issue: https://github.com/HubSpot/hubspot-api-ruby/issues/156
=> With http methdos

CHANGELOG.md, Gemfile.lock, lib/hubspot/discovery/base_api_client.rb, lib/hubspot/discovery/cms/audit_logs/api/audit_logs_api.rb, lib/hubspot/discovery/cms/blogs/blog_posts/api/blog_posts_api.rb, lib/hubspot/discovery/cms/site_search/api/public_api.rb, lib/hubspot/discovery/cms/source_code/api/content_api.rb, lib/hubspot/discovery/cms/source_code/api/extract_api.rb, lib/hubspot/discovery/cms/source_code/api/metadata_api.rb, lib/hubspot/discovery/cms/source_code/api/source_code_extract_api.rb, lib/hubspot/discovery/cms/source_code/api/validation_api.rb, lib/hubspot/discovery/cms/url_redirects/api/redirects_api.rb, lib/hubspot/discovery/conversations/visitor_identification/api/generate_api.rb, lib/hubspot/helpers/path.rb, lib/hubspot/version.rb, spec/discovery/base_api_client_spec.rb
Issue: https://github.com/HubSpot/hubspot-api-ruby/issues/163
This mapping should be removed later with a re-gen.
=> Codegen mapping fix

CHANGELOG.md, Gemfile.lock, lib/hubspot/discovery/base_api_client.rb, lib/hubspot/version.rb
Issue: https://github.com/HubSpot/hubspot-api-ruby/issues/179
Looks like it needs another solution or should be just left as it is.
=> Remove passing params with snake case

CHANGELOG.md, Gemfile.lock, lib/hubspot/discovery/base_api_client.rb, lib/hubspot/version.rb, spec/discovery/base_api_client_spec.rb
Issue: https://github.com/HubSpot/hubspot-api-ruby/issues/181
=> Auth name change

lib/hubspot/discovery/crm/objects/client.rb, lib/hubspot/discovery/crm/objects/postal_mail/api/associations_api.rb, lib/hubspot/discovery/crm/objects/postal_mail/api/basic_api.rb, lib/hubspot/discovery/crm/objects/postal_mail/api/batch_api.rb, lib/hubspot/discovery/crm/objects/postal_mail/api/public_object_api.rb, lib/hubspot/discovery/crm/objects/postal_mail/api/search_api.rb, lib/hubspot/discovery/crm/objects/postal_mail/client.rb, spec/discovery/crm/objects/postal_mail/associations_api_spec.rb, spec/discovery/crm/objects/postal_mail/basic_api_spec.rb, spec/discovery/crm/objects/postal_mail/batch_api_spec.rb, spec/discovery/crm/objects/postal_mail/public_object_api_spec.rb, spec/discovery/crm/objects/postal_mail/search_api_spec.rb
- add postal mail discovery
- add tests for postal mail discovery
=> add postal mail discovery

CHANGELOG.md
=> change update version date

CHANGELOG.md, Gemfile.lock, lib/hubspot/version.rb
- bump version to 16.1.1
- grammar fix
=> bump version to 16.1.1

README.md
=> add search example in README

lib/hubspot/helpers/get_all_helper.rb
- add a possibility to set a limit param for `get_all` method
=> add a possibility to set alimit param for get_all method

lib/hubspot/exceptions.rb, lib/hubspot/helpers/signature.rb, spec/helpers/signature_spec.rb
-  add custom exceptions for signature
- update tests
=>  add custom exceptions for signature

lib/hubspot/client.rb, lib/hubspot/discovery/oauth/client.rb, lib/hubspot/helpers/camel_case.rb, lib/hubspot/helpers/path.rb, lib/hubspot/helpers/snake_case.rb, spec/discovery/client_spec.rb, spec/discovery/oauth/access_tokens_api_spec.rb, spec/discovery/oauth/refresh_tokens_api_spec.rb, spec/discovery/oauth/tokens_api_spec.rb
- change o_auth call path( from `api_client.o_auth` to `api_client.oauth`)
=> change o_auth call path

lib/hubspot/helpers/path.rb
=> update path helper

CHANGELOG.md
- crm.imports
- crm.lists
- crm.owners
- crm.pipelines
- crm.properties
- crm.schemas
- crm.timeline
=> Changelog: Update for CRM

CHANGELOG.md
- crm.companies
- crm.contacts
- crm.deals
=> Changelog: Update for Crm objects

lib/hubspot/discovery/crm/line_items/api/gdpr_api.rb, lib/hubspot/discovery/crm/line_items/client.rb, lib/hubspot/discovery/crm/products/api/gdpr_api.rb, lib/hubspot/discovery/crm/products/client.rb, lib/hubspot/discovery/crm/quotes/api/gdpr_api.rb, lib/hubspot/discovery/crm/quotes/client.rb, lib/hubspot/discovery/crm/tickets/api/gdpr_api.rb, lib/hubspot/discovery/crm/tickets/client.rb, lib/hubspot/helpers/camel_case.rb, spec/discovery/crm/line_items/gdpr_api_spec.rb, spec/discovery/crm/products/gdpr_api_spec.rb, spec/discovery/crm/quotes/gdpr_api_spec.rb, spec/discovery/crm/tickets/gdpr_api_spec.rb
- line_items
- products
- quotes
- tickets
- update camel_case helper
=> Update discoveries, helpers

CHANGELOG.md
- objects
- goals
- calls
- communications
=> Changelog: Update for CrmObjects

lib/hubspot/discovery/crm/contacts/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/emails/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/emails/client.rb, lib/hubspot/discovery/crm/objects/feedback_submissions/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/feedback_submissions/client.rb, lib/hubspot/discovery/crm/objects/goals/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/meetings/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/meetings/client.rb, lib/hubspot/discovery/crm/objects/notes/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/notes/client.rb, lib/hubspot/discovery/crm/objects/postal_mail/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/postal_mail/client.rb, lib/hubspot/discovery/crm/objects/tasks/api/gdpr_api.rb, lib/hubspot/discovery/crm/objects/tasks/client.rb, spec/discovery/crm/contacts/gdpr_api_spec.rb, spec/discovery/crm/objects/emails/gdpr_api_spec.rb, spec/discovery/crm/objects/feedback_submissions/gdpr_api_spec.rb, spec/discovery/crm/objects/meetings/gdpr_api_spec.rb, spec/discovery/crm/objects/notes/gdpr_api_spec.rb, spec/discovery/crm/objects/postal_mail/gdpr_api_spec.rb, spec/discovery/crm/objects/tasks/gdpr_api_spec.rb
- objects
- email
- meetings
- notes
- postal_mail
- tasks
- taxes
- feedback_submissions
- contacts
- goals
=> Crm Objects: Update Discoveries

lib/hubspot/codegen/conversations/visitor_identification/api/generate_api.rb
- Codegen Conversations Visitor Identification
=> Codegen: Conversations Visitor Identification

lib/hubspot/codegen/settings/users/api/roles_api.rb, lib/hubspot/codegen/settings/users/api/teams_api.rb, lib/hubspot/codegen/settings/users/api/users_api.rb, lib/hubspot/codegen/settings/users/api_client.rb, lib/hubspot/codegen/settings/users/api_error.rb, lib/hubspot/codegen/settings/users/configuration.rb, lib/hubspot/codegen/settings/users/models/collection_response_public_permission_set_no_paging.rb, lib/hubspot/codegen/settings/users/models/collection_response_public_team_no_paging.rb, lib/hubspot/codegen/settings/users/models/collection_response_public_user_forward_paging.rb, lib/hubspot/codegen/settings/users/models/error.rb, lib/hubspot/codegen/settings/users/models/error_detail.rb, lib/hubspot/codegen/settings/users/models/forward_paging.rb, lib/hubspot/codegen/settings/users/models/next_page.rb, lib/hubspot/codegen/settings/users/models/public_permission_set.rb, lib/hubspot/codegen/settings/users/models/public_team.rb, lib/hubspot/codegen/settings/users/models/public_user.rb, lib/hubspot/codegen/settings/users/models/public_user_update.rb, lib/hubspot/codegen/settings/users/models/user_provision_request.rb
=> Codegen: Settings

lib/hubspot/codegen/crm/extensions/calling/api/recording_settings_api.rb
- Regenerate Crm Extensions Calling
=> Regenerate: Crm Extensions Calling

lib/hubspot/codegen/marketing/events/api/basic_api.rb, lib/hubspot/codegen/marketing/events/api/list_associations_api.rb
=> Regenerate Marketing Events

README.md, lib/hubspot/client.rb, lib/hubspot/helpers/requests/http_auth.rb, lib/hubspot/helpers/requests/http_request_builder.rb, spec/discovery/client_spec.rb, spec/helpers/requests/http_auth_spec.rb, spec/helpers/requests/http_request_spec.rb
- add api_request
- add tests
- add example using api_request
=> Add api_request

lib/hubspot/codegen/crm/lists/models/public_form_submission_filter_coalescing_refine_by.rb, lib/hubspot/codegen/crm/lists/models/public_indexed_time_point_index_reference.rb, lib/hubspot/codegen/crm/lists/models/public_property_association_filter_branch_filter_branches_inner.rb, lib/hubspot/codegen/crm/lists/models/public_property_association_filter_branch_filters_inner.rb, lib/hubspot/codegen/crm/lists/models/public_survey_monkey_value_filter_value_comparison.rb, lib/hubspot/codegen/crm/lists/models/public_time_point_operation_time_point.rb, lib/hubspot/helpers/signature.rb
https://github.com/HubSpot/hubspot-api-ruby/pull/360
=> Codegen Crm Lists

lib/hubspot/codegen/cms/hubdb/models/standard_error.rb, lib/hubspot/codegen/cms/hubdb/models/unified_collection_response_with_total_base_hub_db_table_row_v3.rb, lib/hubspot/helpers/signature.rb
https://github.com/HubSpot/hubspot-api-ruby/pull/360
=> Codegen Cms Hubdb

lib/hubspot/codegen/crm/extensions/calling/api/channel_connection_settings_api.rb, lib/hubspot/codegen/crm/extensions/calling/api/recording_settings_api.rb, lib/hubspot/codegen/crm/extensions/calling/models/channel_connection_settings_patch_request.rb, lib/hubspot/codegen/crm/extensions/calling/models/channel_connection_settings_request.rb, lib/hubspot/codegen/crm/extensions/calling/models/channel_connection_settings_response.rb, lib/hubspot/codegen/crm/extensions/calling/models/recording_settings_response.rb, lib/hubspot/codegen/crm/extensions/calling/models/settings_request.rb, lib/hubspot/codegen/crm/extensions/calling/models/settings_response.rb
=> Codegen Crm Extensions Calling

lib/hubspot/codegen/cms/blogs/blog_posts/api/basic_api.rb
=> Regen Cms Blogs BlogPosts
